/* Note: Comments are Generated by AI using chatgpt */

#include "crc.h"  // Include the header file that defines the CRC_Handle_t structure and function prototypes

/**
 * @brief  Initializes the CRC module by setting the CRC register to the initial value.
 * @param  hcrc: Pointer to the CRC handle structure, which contains the CRC configuration.
 * @retval The initial CRC value set in the CRC register.
 */
void
CRC32_Init (CRC_Handle_t *hcrc)
{
  if (!hcrc->crc_poly)
    { /* Check if the crc not initialized */
      hcrc->crc_initval = DEFAULT_INIT_VAL;
      hcrc->crc_poly = DEFAULT_POLY_VAL;
    }
  hcrc->crc_reg = hcrc->crc_initval; // Set the CRC register to the initial value specified in the handle
}

/**
 * @brief  Calculates the CRC32 for the given data buffer.
 * @param  hcrc: Pointer to the CRC handle structure, which contains the CRC configuration and state.
 * @param  data: Pointer to the data buffer for which the CRC is to be calculated.
 * @param  length: Length of the data buffer.
 * @retval The computed CRC32 value.
 */
uint32_t
CRC32_Calculate (CRC_Handle_t *hcrc, uint8_t *data, uint32_t length)
{
  uint32_t crc = hcrc->crc_reg; // Get the current CRC value from the handle (initial or updated value)
  uint32_t poly = hcrc->crc_poly; // Get the CRC polynomial from the handle

  // Iterate over each byte in the data buffer
  for (size_t i = 0; i < length; i++)
    {
      crc ^= data[i]; // XOR the current byte of data with the current CRC value
      // Process each bit of the byte
      for (int j = 0; j < 8; j++)
	{
	  if (crc & 1)
	    {  // If the least significant bit is 1
	      crc = (crc >> 1) ^ poly; // Shift right and XOR with the polynomial
	    }
	  else
	    {
	      crc >>= 1;  // Otherwise, just shift right
	    }
	}
    }

  hcrc->crc_reg = ~crc; // Invert all the bits (final XOR step) and store it in the CRC register
  return hcrc->crc_reg;  // Return the final CRC value
}

/**
 * @brief  Resets the CRC register to the initial value.
 * @param  hcrc: Pointer to the CRC handle structure.
 */
void
CRC32_ResetCRC (CRC_Handle_t *hcrc)
{
  hcrc->crc_reg = hcrc->crc_initval; // Reset the CRC register to the initial value specified in the handle
}
